const mongoose = require("mongoose");

const generalSettingSchema = new mongoose.Schema(
  {
    selectedCurrencyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Currency",
      default: null,
    },
    websiteTitle: { type: String, required: true },
    supportNumber: { type: String },
    guestcheckout: { type: Boolean },
    supportEmail: { type: String },
    copyrightText: { type: String },
    address: { type: String },
    //mapFrame: { type: String },
    logo: { type: String }, // store image path or URL
    footerLogo: { type: String },
    favicon: { type: String }, // store image path or URL
    sticky: { type: String },
    adminLogo: { type: String },
    invoiceLogo: { type: String },
    facebook: { type: String },
    twitter: { type: String },
    instagram: { type: String },
    youtube: { type: String },
    metaKeywords: { type: String },
    metaTitle: { type: String },
    metaDescription: { type: String },
    storeSlug: { type: String, required: true, unique: false },
    primaryFont: { type: String, default: "Inter" },
    secondaryFont: { type: String, default: "Inter" },
    tertiaryFont: { type: String, default: "Inter" },
    bodyFontAssignment: { type: String, default: "primary" },
    headingFontAssignment: { type: String, default: "primary" },
    productCardLayout: { type: String, default: "layout-1" },
    showAddToCart: { type: Boolean, default: true },
    showWishlist: { type: Boolean, default: true },
    showProductRating: { type: Boolean, default: true },
    showSaleBadge: { type: Boolean, default: true },
    showBuyNow: { type: Boolean, default: true },
    showSelectedImageThumbnail: { type: Boolean, default: true },
    showImageOnlyOnHover: { type: Boolean, default: false },
    productCardBgColor: { type: String, default: "#ffffff" },
    productCardTextColor: { type: String, default: "#111111" },
    productCardBorderColor: { type: String, default: "#e2e8f0" },
    productCardHoverBorderColor: { type: String, default: "#cbd5e1" },
    isSearchTypewriterEnabled: { type: Boolean, default: true },
    isVoiceSearchEnabled: { type: Boolean, default: true },
    searchPlaceholders: { type: String, default: "Jeans, Shirt, Shoes, Watches, Hoodies, Sunglasses, T-Shirts" },
    additionalCss: { type: String, default: "" },
    additionalJs: { type: String, default: "" },
    isStorefrontPasswordEnabled: { type: Boolean, default: true },
    storefrontPassword: { type: String, default: "magic" },
    showDummyData: { type: Boolean, default: false },
    btnStyle: { type: String, default: "solid" },
    btnBgColor: { type: String, default: "#000000" },
    btnTextColor: { type: String, default: "#ffffff" },
    btnBorderColor: { type: String, default: "#000000" },
    btnHoverBgColor: { type: String, default: "#111111" },
    btnHoverTextColor: { type: String, default: "#ffffff" },
    btnHoverBorderColor: { type: String, default: "#111111" },
    btnBorderWidth: { type: Number, default: 1 },
    btnBorderRadius: { type: Number, default: 8 },
    productCardBorderRadius: { type: Number, default: 12 },
    productImageBorderRadius: { type: Number, default: 8 },
    showCardBorderRadius: { type: Boolean, default: true },
    showImageBorderRadius: { type: Boolean, default: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("GeneralSetting", generalSettingSchema);
